# Generated by Django 5.2 on 2025-09-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopaciente',
            old_name='tipo_de_sangre',
            new_name='sexo',
        ),
    ]
