# Generated by Django 5.2 on 2025-09-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_tipo_de_sangre_usuariopaciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopaciente',
            name='correo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariopaciente',
            name='telefono',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
