# Generated by Django 5.2 on 2025-10-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuariopaciente_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('codigo_estudiante', models.CharField(max_length=9, unique=True)),
                ('semestre', models.IntegerField()),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
    ]
