# Generated by Django 5.2 on 2025-10-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarioestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioestudiante',
            name='area',
            field=models.CharField(blank=True, choices=[('Diagnóstico', 'Diagnóstico'), ('Especialidad', 'Especialidad')], max_length=20, null=True),
        ),
    ]
