# Generated by Django 5.2 on 2025-10-04 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuarioestudiante_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('analisis_requeridos', models.TextField(blank=True, null=True)),
                ('codigo_tarjeton', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarioestudiante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariopaciente')),
            ],
        ),
    ]
