# Generated by Django 5.2 on 2025-10-04 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_citadiagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citadiagnostico',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuarioestudiante'),
        ),
    ]
