# Generated by Django 5.2 on 2025-10-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_citadiagnostico_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='citadiagnostico',
            name='edad_paciente',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citadiagnostico',
            name='nombre_paciente',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citadiagnostico',
            name='codigo_tarjeton',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
