# Generated by Django 5.2 on 2025-10-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_citadiagnostico_edad_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='citadiagnostico',
            old_name='analisis_requeridos',
            new_name='otros_estudios',
        ),
        migrations.AddField(
            model_name='citadiagnostico',
            name='estudios_requeridos',
            field=models.ManyToManyField(blank=True, to='usuarios.tipoestudio'),
        ),
    ]
