# Generated by Django 5.2 on 2025-10-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_tipoestudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citadiagnostico',
            name='especialidad_asignada',
            field=models.CharField(blank=True, choices=[('Endodoncia', 'Endodoncia'), ('Ortodoncia', 'Ortodoncia'), ('Periodoncia', 'Periodoncia'), ('Prótesis', 'Prótesis'), ('Cirugía Oral', 'Cirugía Oral')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='citadiagnostico',
            name='habilitada_especialidad',
            field=models.BooleanField(default=False),
        ),
    ]
