# Generated by Django 5.2 on 2025-10-10 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_citadiagnostico_especialidad_asignada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('edad_paciente', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('especialidad', models.CharField(choices=[('Endodoncia', 'Endodoncia'), ('Ortodoncia', 'Ortodoncia'), ('Periodoncia', 'Periodoncia'), ('Prótesis', 'Prótesis'), ('Cirugía Oral', 'Cirugía Oral')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_tarjeton', models.CharField(blank=True, max_length=20, null=True)),
                ('atendida', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuarioestudiante')),
                ('habilitada_por', models.ForeignKey(blank=True, help_text='Cita de diagnóstico que autorizó esta cita.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.citadiagnostico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariopaciente')),
            ],
        ),
    ]
