# Generated by Django 5.2 on 2025-10-10 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_citaespecialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citaespecialidad',
            name='atendida',
        ),
        migrations.AlterField(
            model_name='citadiagnostico',
            name='especialidad_asignada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='citaespecialidad',
            name='especialidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='citaespecialidad',
            name='habilitada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.citadiagnostico'),
        ),
    ]
