# Generated by Django 5.2 on 2025-10-11 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_citaespecialidad_atendida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citadiagnostico',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_diagnostico_asignadas', to='usuarios.usuarioestudiante'),
        ),
        migrations.AlterField(
            model_name='citadiagnostico',
            name='estudios_requeridos',
            field=models.ManyToManyField(blank=True, related_name='citas_diagnostico', to='usuarios.tipoestudio'),
        ),
        migrations.AlterField(
            model_name='citadiagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_diagnostico', to='usuarios.usuariopaciente'),
        ),
        migrations.AlterField(
            model_name='citaespecialidad',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_especialidad_asignadas', to='usuarios.usuarioestudiante'),
        ),
        migrations.AlterField(
            model_name='citaespecialidad',
            name='habilitada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_especialidad_derivadas', to='usuarios.citadiagnostico'),
        ),
        migrations.AlterField(
            model_name='citaespecialidad',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_especialidad', to='usuarios.usuariopaciente'),
        ),
    ]
