# Generated by Django 5.2 on 2025-10-11 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_citadiagnostico_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadHabilitadaPorPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
                ('cita_diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.citadiagnostico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariopaciente')),
            ],
        ),
    ]
