# Generated by Django 5.2 on 2025-10-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_especialidadhabilitadaporpaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopaciente',
            name='sexo',
            field=models.CharField(max_length=30),
        ),
    ]
