# Generated by Django 5.2 on 2025-10-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_usuariopaciente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioestudiante',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuarioestudiante',
            name='horario',
            field=models.FileField(blank=True, null=True, upload_to='horarios/'),
        ),
    ]
