# Generated by Django 5.2 on 2025-10-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_usuarioestudiante_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioestudiante',
            name='horario',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
