# Generated by Django 5.2 on 2025-10-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_usuarioestudiante_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaespecialidad',
            name='sexo_paciente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='citaespecialidad',
            name='telefono_paciente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
