# Generated by Django 5.2 on 2025-11-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_citaespecialidad_sexo_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaFinalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('edad_paciente', models.IntegerField()),
                ('sexo_paciente', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_paciente', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('especialidad', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_tarjeton', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_finalizacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarioestudiante')),
            ],
        ),
    ]
