# Generated by Django 5.2 on 2025-11-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_citafinalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='citadiagnostico',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
