# Generated by Django 5.2 on 2025-11-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_citadiagnostico_cancelada'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaespecialidad',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
