# Generated by Django 5.2 on 2025-11-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_citaespecialidad_cancelada'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioestudiante',
            name='direccion_consultorio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
