# Generated by Django 5.2 on 2025-11-11 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_usuarioestudiante_direccion_consultorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='citafinalizada',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariopaciente'),
        ),
    ]
